### ISSUE TITLE
log a specific exception for various connection-level failures

### ISSUE THREAD

**Issue by busterb** [rapid7/msfrpc-client#3]
We currently only send a generic error for everything ranging from TLS issues to wrong credentials. We should be able to do better and say why the client could not connect.

**Comment by bcoles** [comment]
In particular, handling of the following would be nice:

* TCP connection failure
* SSL negotiation failure
* Authentication failure

The above all throw the same error.

**Comment by busterb** [comment]
So, here's what happens with PR #4 

TCP connection failure:
```
>> rpc.login('cow', 'cow')
Rex::ConnectionRefused: The connection was refused by the remote host (127.0.0.1:3790).
```

SSL failure 1:
```
>> rpc.login('cow', 'cow')
Errno::ECONNRESET: Connection reset by peer - SSL_connect
```
SSL failure 2 (I connected it to OpenSSL 0.9.8 which doesn't support TLS 1.2)
```
>> rpc.login('cow', 'cow')
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: dh key too small
```

Failure connecting to the wrong kind of service and getting garbage back (that could use some work)
```
>> rpc.login('cow', 'cow')
RuntimeError: nil
```

**Comment by bcoles** [comment]
Thanks. Works perfectly.
